# Generated by Django 6.0 on 2025-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_toner_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='anulado_motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
